#!/usr/bin/env bash
set -euo pipefail

export XDG_CURRENT_DESKTOP=GNOME
export DESKTOP_SESSION=vnde
export LANG=vi_VN.UTF-8
export LANGUAGE=vi_VN:vi
export LC_TIME=vi_VN.UTF-8
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus

exec gnome-session --session=gnome
