#!/usr/bin/env bash
set -euo pipefail

export XDG_CURRENT_DESKTOP=VNDE
export DESKTOP_SESSION=vnde
export GTK_THEME=Adwaita:dark
export LANG=vi_VN.UTF-8
export LANGUAGE=vi_VN:vi
export LC_TIME=vi_VN.UTF-8
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus

mkdir -p "$HOME/.config/vnde"
"$HOME/.config/vnde/scripts/autostart.sh" &
exec openbox --config-file "$HOME/.config/vnde/openbox/rc.xml"
